server:
  port: 8989
  servlet:
    context-path: /ems
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ancx
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: info
    com.baizhi.dao: debug